apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: aous1/livraison_c:latest
        ports:
        - containerPort: 88
        
        
---

apiVersion: v1
kind: Service
metadata:
   name: node-service
   labels:
     app: node-service
      
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 3000
       targetPort: 88
   selector:
     app: node-pod
