apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: cd-project
          image: aous1/livraison_c:latest
          ports:
            - containerPort: 80
---

---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 80
    nodePort: 30300
