---
# tasks file for docker
- name: create image docker 
  docker_image:
    name: liveraison_c
    build:
     path: /var/lib/jenkins/workspace/liveraison_c
     pull: no		
    source: build
    state: present
    force_source: true
- name: run container docker
  docker_container:
    name: aous_lc
    image: liveraison_c:latest
    state: started
    recreate: true
    ports:
     - "4200:80"
